import { useEffect, useRef, useState } from "react";
import InfoPanel from "./InfoPanel";
import * as d3 from "d3";
import defaultGraphData from "../input/input.json";
// import defaultGraphData from "../../analyzer/tests/expected/+classic.json";
import { CircleAlert, CircleCheck, MoveUpRight } from "lucide-react";
import { ControlFlowGraph } from "./controlFlowGraph";

interface MutexGraphProps {
  buttonState: boolean;
  setButtonState: any;
  justAddedData: any;
  setJustAddedData: any;
}

const MutexGraph: React.FC<MutexGraphProps> = ({ buttonState, setButtonState, justAddedData, setJustAddedData }) => {
  const [graphData, setGraphData] = useState<any>(defaultGraphData);
  const [currentFileName, setCurrentFileName] =
    useState<string>("sample_input.json");
  const [selectedElement, setSelectedElement] = useState<any>(null);
  const [selectedType, setSelectedType] = useState<"node" | "edge" | null>(
    null
  );
  const [windowSize, setWindowSize] = useState({ width: 0, height: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const svgRef = useRef<SVGSVGElement>(null);
  const [hasDeadlock, setHasDeadlock] = useState<boolean>(false);

  useEffect(() => {
    if (graphData && windowSize.width > 0) {
      renderGraph();
    }
  }, [graphData, windowSize, buttonState]);

  useEffect(() => {
    const updateWindowSize = () => {
      if (containerRef.current) {
        const width = containerRef.current.clientWidth;
        const height = containerRef.current.clientHeight;
        setWindowSize({ width, height });
      }
    };

    updateWindowSize();
  }, [buttonState]);

  // const deadlockEdges = new Map<string, { target: string; type: string }>();
  // const deadlockMap = new Map<string, boolean>();

  // const [deadlockEdges, setDeadlockEdges] = useState(new Map<string, { target: string; type: string }>());
  const [deadlockMap, setDeadlockMap] = useState(new Map<string, boolean>());

  useEffect(() => {
    const deadlockMapTemp = new Map<string, boolean>();
    // const deadlockEdgesTemp = new Map<string, { target: string; type: string }>();

    // console.log("Graph Data", graphData);
    // console.log("Graph Data edges", graphData.edges);
    graphData.edges?.forEach((edge: any) => {
      if (edge.cycle) {
        if (typeof edge.source === "string") {
          deadlockMapTemp.set(edge.source, true);
        } else {
          deadlockMapTemp.set(edge.source.id, true);
        }

        if (typeof edge.target === "string") {
          deadlockMapTemp.set(edge.target, true);
        } else {
          deadlockMapTemp.set(edge.targetid, true);
        }
        // deadlockMapTemp.set(edge.source, true);
        // deadlockMapTemp.set(edge.target, true);
        // deadlockEdgesTemp.set(edge.source, {
        //   target: edge.target,
        //   type: edge.type,
        // });
      }
    });

    // setDeadlockEdges(deadlockEdgesTemp);
    setDeadlockMap(deadlockMapTemp);
    // console.log("DEADLOCK MAP TEMP", deadlockMapTemp);
  }, [graphData]);

  /** Contains Code Generated by ChatGPT on Fri Mar 21 */
  // lots of code basis from https://observablehq.com/@d3/mobile-patent-suits
  // used ChatGPT for debugging
  const renderGraph = () => {
    const { width, height } = windowSize;

    const svg = d3.select(svgRef.current);

    svg.selectAll("*").remove(); // add this to reset graph on re-render

    svg
      .attr("width", width)
      .attr("height", height)
      .attr("viewBox", [0, 0, width, height])
      .style("background-color", "#fafafa");

    const nodeMap = new Map(
      graphData.nodes.map((node: any) => [node.id, node])
    );

    const simulation = d3
      .forceSimulation()
      .force(
        "link",
        d3
          .forceLink()
          .id((d: any) => d.id)
          .distance(180) // this sets minimum distance when using force link, else squished
      )
      .force("charge", d3.forceManyBody().strength(-200))
      .force("center", d3.forceCenter(width / 2, height / 2));

    const deadlockEdges = new Map<string, { target: string; type: string }>();
    // Unsure what "deadlocks": [["resource1", "resource2"]], means, so I am just
    // looping through all [...] in deadlocks, and for each [...] I loop within
    // them and set those for deadlock = true

    graphData.edges?.forEach((edge: any) => {
      if (edge.cycle) {
        deadlockEdges.set(edge.source, {
          target: edge.target,
          type: edge.type,
        });
      }
    });

    graphData.nodes.forEach((node: any) => {
      if (!deadlockMap.has(node.id)) {
        deadlockMap.set(node.id, false);
      }
    });

    const hasDeadlockCycles = graphData.deadlocks;
    setHasDeadlock(hasDeadlockCycles);

    // @ts-ignore
    const newGraphData = graphData.edges.filter((edge: any) => {
      return edge.type == "waiting";
    });

    svg
      .append("defs")
      .selectAll("marker")
      .data(["arrow", "arrow-deadlock"])
      .enter()
      .append("marker")
      .attr("id", (d: any) => d)
      .attr("viewBox", "0 -5 10 10")
      .attr("refX", 20)
      .attr("refY", 0)
      .attr("markerWidth", 8)
      .attr("markerHeight", 8)
      .attr("orient", "auto")
      .append("path")
      .attr("fill", (d) => (d === "arrow-deadlock" ? "#b91c1c" : "#57534e"))
      .attr("d", "M0,-5L10,0L0,5");

    const link = svg
      .append("g")
      .attr("class", "links")
      .selectAll("g")
      .data(graphData.edges)
      .enter()
      .append("g");

    const lines = link
      .append("path")
      .attr("class", "link")
      .attr("stroke", (d: any) => {
        return deadlockEdges.get(d.source)?.type === "waiting"
          ? "#b91c1c"
          : "#57534e";
      })
      .attr("stroke-width", 4)
      .attr("fill", "none")
      .attr("marker-end", (d: any) => {
        return deadlockEdges.get(d.source)?.type === "waiting"
          ? "url(#arrow-deadlock)"
          : "url(#arrow)";
      })
      .on("click", (_, d) => {
        setSelectedElement(d);
        setSelectedType("edge");
      });

    const edgeLabels = link
      .append("text")
      .attr("class", "edge-label")
      .attr("dy", -5)
      .attr("text-anchor", "middle")
      .attr("font-size", "12px")
      .text((d: any) => `${d.function}`)
      .on("click", (_, d) => {
        setSelectedElement(d);
        setSelectedType("edge");
      });

    const node = svg
      .append("g")
      .attr("class", "nodes")
      .selectAll("g")
      .data(graphData.nodes)
      .enter()
      .append("g")
      .call(
        d3
          .drag<SVGGElement, unknown>()
          .on("start", dragStarted)
          .on("drag", dragged)
          .on("end", dragEnded)
      );

    node
      .append("circle")
      .attr("r", 42)
      .attr("fill", function (d: any) {
        if (d.type === "process") {
          return "#000000";
        } else {
          return "transparent";
        }
      })
      .attr("opacity", 0.1)
      .attr("transform", "translate(3, 3)");

    node
      .append("circle")
      .attr("r", 40)
      .attr("fill", function (d: any) {
        if (d.type === "process") {
          // console.log("TEST", deadlockMap);
          // console.log("TEST2", d.id);
          if (deadlockMap.get(d.id)) {
            return "#fecaca";
          } else {
            return "#bae6fd";
          }
        } else {
          return "transparent";
        }
      })
      .attr("stroke", function (d: any) {
        if (d.type === "process") {
          if (deadlockMap.get(d.id)) {
            return "#b91c1c";
          } else {
            return "#0c4a6e";
          }
        } else {
          return "transparent";
        }
      })
      .attr("stroke-width", 4)
      .on("click", (_, d) => {
        setSelectedElement(d);
        setSelectedType("node");
      });

    node
      .append("rect")
      .attr("x", -30)
      .attr("y", -30)
      .attr("width", 60)
      .attr("height", 60)
      .attr("fill", function (d: any) {
        if (d.type === "resource") {
          if (deadlockMap.get(d.id)) {
            return "#fecaca";
          } else {
            return "#bae6fd";
          }
        } else {
          return "transparent";
        }
      })
      // (deadlockMap.get(d.id) ? "#fecaca" : "#bae6fd")
      .attr("stroke", function (d: any) {
        if (d.type === "resource") {
          if (deadlockMap.get(d.id)) {
            return "#b91c1c";
          } else {
            return "#0c4a6e";
          }
        } else {
          return "transparent";
        }
      })
      .attr("stroke-width", 4)
      .on("click", (_, d) => {
        setSelectedElement(d);
        setSelectedType("node");
      });

    node
      .append("text")
      .attr("dy", 5)
      .attr("text-anchor", "middle")
      .attr("font-weight", "bold")
      .attr("font-size", "12px")
      .text((d: any) => `${d.id}`)
      .on("click", (_, d) => {
        setSelectedElement(d);
        setSelectedType("node");
      });

    simulation.nodes(graphData.nodes as any);
    simulation
      .force<d3.ForceLink<any, any>>("link")
      ?.links(graphData.edges as any); // So nodes don't float away
    simulation.on("tick", () => {
      graphData.nodes.forEach((d: any) => {
        d.x = Math.max(40, Math.min(width - 40, d.x));
        d.y = Math.max(40, Math.min(height - 40, d.y));
      });
      lines.attr("d", (d: any) => {
        const sourceNode = d.source.id ? d.source : nodeMap.get(d.source); // from chatGPT Fri Mar 21, needed to make force link work
        const targetNode = d.target.id ? d.target : nodeMap.get(d.target);

        if (!sourceNode || !targetNode) return "";

        const sourceX = sourceNode.x;
        const sourceY = sourceNode.y;
        const targetX = targetNode.x;
        const targetY = targetNode.y;

        const reciprocal = graphData.edges.find(
          (e: any) => e.source === d.target && e.target === d.source
        );

        // this makes the arrows curved if reciprocal (meaning <--> arrow)
        // otherwise it uses straight arrows
        if (reciprocal) {
          const dx = targetX - sourceX;
          const dy = targetY - sourceY;
          const dr = Math.sqrt(dx * dx + dy * dy);
          const midX = (sourceX + targetX) / 2;
          const midY = (sourceY + targetY) / 2;

          const offsetX = (-dy / dr) * 20;
          const offsetY = (dx / dr) * 20;

          return `M${sourceX},${sourceY} Q${midX + offsetX},${
            midY + offsetY
          } ${targetX},${targetY}`;
        } else {
          return `M${sourceX},${sourceY} L${targetX},${targetY}`;
        }
      });
      node.attr("transform", (d: any) => `translate(${d.x}, ${d.y})`);
      edgeLabels.attr("transform", (d: any) => {
        // this is mostly copied from the lines code above, may want to
        // clean up this code
        const sourceNode = d.source.id ? d.source : nodeMap.get(d.source);
        const targetNode = d.target.id ? d.target : nodeMap.get(d.target);

        if (!sourceNode || !targetNode) return "";

        const sourceX = sourceNode.x;
        const sourceY = sourceNode.y;
        const targetX = targetNode.x;
        const targetY = targetNode.y;

        const reciprocal = graphData.edges.find(
          (e: any) => e.source === d.target && e.target === d.source
        );

        if (reciprocal) {
          const dx = targetX - sourceX;
          const dy = targetY - sourceY;
          const dr = Math.sqrt(dx * dx + dy * dy);

          const offsetX = (-dy / dr) * 20;
          const offsetY = (dx / dr) * 20;

          const midX = (sourceX + targetX) / 2 + offsetX;
          const midY = (sourceY + targetY) / 2 + offsetY;

          return `translate(${midX}, ${midY})`;
        } else {
          const midX = (sourceX + targetX) / 2;
          const midY = (sourceY + targetY) / 2;
          return `translate(${midX}, ${midY})`;
        }
      });
    });

    function dragStarted(event: any, d: any) {
      if (!event.active) simulation.alphaTarget(0.3).restart();
      d.fx = d.x;
      d.fy = d.y;
    }

    function dragged(event: any, d: any) {
      d.fx = event.x;
      d.fy = event.y;
    }

    function dragEnded(event: any, d: any) {
      if (!event.active) simulation.alphaTarget(0);
      d.fx = null;
      d.fy = null;
    }
  };

  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);

    setButtonState(false);
    setJustAddedData(true);

    const files = e.dataTransfer.files;
    if (files.length > 0) {
      if (files.length > 1) {
        alert("Please only one file :)");
      } else {
        const file = files[0];
        // console.log(file.type);
        if (file.type === "application/json") {
          const reader = new FileReader();

          reader.onload = (event) => {
            try {
              const result = event.target?.result;
              if (typeof result === "string") {
                const jsonData = JSON.parse(result);
                setGraphData(jsonData);
                setCurrentFileName(file.name);
              } else {
                console.log("ERROR: result is not string...");
              }
            } catch (error) {
              console.log("ERROR: parsing JSON file", error);
              alert("Please enter valid JSON :)");
            }
          };

          reader.readAsText(file);
        } else {
          alert("Please drop only JSON file :)");
        }
      }
    }
  };

  return (
    <>
  {!buttonState &&
          <ControlFlowGraph graphData={graphData} justAddedData={justAddedData} />
        }
  {buttonState &&
    <div className="flex flex-row gap-4 h-full">
      <div
        ref={containerRef}
        className="flex-1 min-h-96 bg-blue-300 relative"
        onDrop={handleDrop}
        onDragOver={handleDragOver}
        onDragLeave={() => setIsDragging(false)}
      >
          <svg
          ref={svgRef}
          className={`w-full h-full border border-gray-300 bg-white`}
        ></svg>

        <div className="absolute top-4 right-4 bg-white p-4 border border-gray-300">
          <div className="font-semibold pb-2 mb-4 border-b border-gray-100">
            {hasDeadlock ? (
              <div className="flex items-center gap-2 text-red-700">
                <CircleAlert className="w-5 h-5" />
                <div className="text-red-700">Potential Deadlock Detected</div>
              </div>
            ) : (
              <div className="flex items-center gap-2 text-sky-700">
                <CircleCheck className="w-5 h-5" />
                <div className="text-sky-900">No Deadlock Detected</div>
              </div>
            )}
          </div>
          <div className="flex flex-col space-y-2">
            <div className="flex items-center">
              <div className="w-5 h-5 rounded-full bg-sky-200 border-2 border-sky-900 mr-2" />
              <span className="text-sm text-zinc-700">Normal process</span>
            </div>
            <div className="flex items-center pl-0.5">
              <div className="w-4 h-4 bg-sky-200 border-2 border-sky-900 mr-2.5" />
              <span className="text-sm text-zinc-700">Normal mutex</span>
            </div>
            <div className="flex items-center">
              <div className="w-5 h-5 rounded-full bg-red-200 border-2 border-red-800 mr-2" />
              <span className="text-sm text-zinc-700">
                Potential deadlock process
              </span>
            </div>
            <div className="flex items-center pl-0.5">
              <div className="w-4 h-4 bg-red-200 border-2 border-red-800 mr-2.5" />
              <span className="text-sm text-zinc-700">
                Potential deadlock mutex
              </span>
            </div>
            <div className="flex items-center">
              <MoveUpRight className="w-5 h-5 text-[#57534e] mr-2" />
              <span className="text-sm text-zinc-700">Holds lock</span>
            </div>
            <div className="flex items-center">
              <MoveUpRight className="w-5 h-5 text-red-800 mr-2" />
              <span className="text-sm text-zinc-700">Waits for</span>
            </div>
          </div>
        </div>

        {isDragging && (
          <div className="absolute inset-0 bg-blue-400 flex items-center justify-center border-4 border-dashed border-blue-200">
            <div className="bg-white p-4 rounded-md">
              <div className="text-blue-500 font-bold">Drop JSON here</div>
            </div>
          </div>
        )}
      </div>
      <div
        className="w-80"
        onDrop={handleDrop}
        onDragOver={handleDragOver}
        onDragLeave={() => setIsDragging(false)}
      >
        <InfoPanel
          selectedElement={selectedElement}
          type={selectedType}
          currentFileName={currentFileName}
          graphData={graphData}
        />
      </div>
    </div>
}
    </>
  );
};

export default MutexGraph;
